language: perl
perl:
    - "5.24"
    - "blead"

services:
      - mysql
dist: trusty
sudo: required

matrix:
    include:
        - perl: "5.24"
          env: COVERAGE=1
    allow_failures:
        - perl: "blead"

before_install:
    - sudo cp /etc/mysql/my.cnf /usr/share/mysql/my-default.cnf
    - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
    - source ~/travis-perl-helpers/init
    - build-perl
    - perl -V
    - build-dist
    - cd $BUILD_DIR

install:
    - cpan-install --deps
    - cpan-install --coverage

before_script:
    - coverage-setup

script:
    - perl Makefile.PL
    - make
    - prove -bl -s -j$(test-jobs) $(test-files)

after_success:
    - coverage-report
