#!/bin/bash
. /opt/local/perlbrew/etc/bashrc
eval $( perl -Mlocal::lib )

export MOJO_HOME=$(pwd)
export BEAM_MINION=sqlite:////home/cpantesters/var/db/minion.sqlite

exec cpantesters-legacy-metabase prefork -l http://*:8250 -G 1500 -H 300 -i 240  2>&1
